#!/bin/bash
#script to clone trees

USERNAME="" #JUST FILL UR GITHUB USERNAME

# DEVICE TREE
DEVICE_REPO="" #JUST FILL THE NAME OF THE DEVICE REPO , NO NEED OF LINK
DEVICE_BRANCH="" #JUST FILL THE BRANCH OF DEVICE TREE REPO
DEVICE_DIR="" #JUST ADD THE LOCATION WHERE U WANT TO CLONE THE TREE

# VENDOR TREE
VENDOR_REPO="" #JUST FILL THE NAME OF THE VENDOR REPO , NO NEED OF LINK
VENDOR_BRANCH="" #JUST FILL THE BRANCH OF VENDOR TREE REPO
VENDOR_DIR="" #JUST ADD THE LOCATION WHERE U WANT TO CLONE THE TREE

# KERNEL
KERNEL_REPO="" #JUST FILL THE NAME OF THE KERNEL REPO , NO NEED OF LINK
KERNEL_BRANCH="" #JUST FILL THE BRANCH OF KERNEL TREE REPO
KERNEL_DIR="" #JUST ADD THE LOCATION WHERE U WANT TO CLONE THE TREE


## DON'T EDITT FROM HERE ##



GITHUB='https://github.com/$USERNAME'

echo -e "\n============== CLONING DEVICE TREE ==============\n"
git clone -b $DEVICE_BRANCH $GITHUB/$DEVICE_REPO $DEVICE_DIR

echo -e "\n============== CLONING VENDOR TREE ==============\n"
git clone -b $VENDOR_BRANCH $GITHUB/$VENDOR_REPO $VENDOR_DIR

echo -e "\n============== CLONING KERNEL ==============\n"
git clone -b $KERNEL_BRANCH $GITHUB/$KERNEL_REPO $KERNEL_DIR


echo -e "\n============== DONE ==============\n"
